config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'password_resets/edit'
    get 'balances/edit'
    root 'pages#mainpage'
    get 'pages/about', as: 'about'
    get 'records/index', as: 'home'

    resources :records do
      resources :comments
    end

    get 'sign_up', to: 'users#new'
    post 'sign_up', to: 'users#create'
    get 'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create', as: 'log_in'
    delete 'logout', to: 'sessions#destroy'

    get 'lk', to: 'users#edit', as: 'edit_balance'
    patch 'lk', to: 'users#update'

    get 'password/reset', to: 'password_resets#new'
    post 'password/reset', to: 'password_resets#create'
    get 'password/reset/edit', to: 'password_resets#edit'
    patch 'password/reset/edit', to: 'password_resets#update'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :record
  validates :username, presence: true
  validates :cost, presence: true, comparison: { greater_than: 0 }
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/record.rb
# frozen_string_literal: true

class Record < ApplicationRecord
  has_one_attached :photo
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 30 }
  validates :photo, presence: true
  validates :description, presence: true, length: { minimum: 100, maximum: 555 }
  validates :status, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# class ApplicationController
class ApplicationController < ActionController::Base
  before_action :set_current_user
  around_action :switch_locale
  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    @is_admin = Current.user.email == 'admin@admin.admin' if Current.user
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: (t 'application.sign_in_alert') if Current.user.nil?
  end

  def require_user_admin!
    redirect_to root_path, alert: (t 'application.not_admin') unless @is_admin
  end

  def switch_locale(&action)
    locale = locale_from_url || I18n.default_locale
    I18n.with_locale locale, &action
  end

  def locale_from_url
    locale = params[:locale]
    return locale if I18n.available_locales.map(&:to_s).include?(locale)

    nil
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# class CommentsController
class CommentsController < ApplicationController
  def create
    @record = Record.find(params[:record_id])
    @comment = @record.comments.create!(username: Current.user.email, cost: comment_params[:cost])
    balance_minus
    redirect_to record_path(@record)
  end

  private

  def comment_params
    params.require(:comment).permit(:cost)
  end

  def balance_minus
    return unless comment_params[:cost].to_i.positive?

    Current.user.balance -= comment_params[:cost].to_i
    Current.user.save
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# class PagesController
class PagesController < ApplicationController
  def mainpage; end

  def about; end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

# class PasswordResetsController
class PasswordResetsController < ApplicationController
  def new; end

  def edit
    # finds user with a valid token
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: (t '.token_exp')
  end

  def update
    # updates user's password
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to sign_in_path, notice: (t '.res_pasw')
    else
      render :edit
    end
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
      # deliver_later is provided by ActiveJob
    end
    redirect_to root_path, notice: (t '.check_email')
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/records_controller.rb
# frozen_string_literal: true

# class RecordsController
class RecordsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :require_user_admin!, except: %i[index show]
  def edit
    @record = Record.find(params[:id])
  end

  def index
    @record = Record.all
  end

  def new
    @record = Record.new
  end

  def show
    @record = Record.find(params[:id])
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      @record.update_column(:timeend, Time.now.next_day)
      RecordsCloseJob.set(wait: 1.days).perform_later(@record)
      redirect_to @record
    else
      render 'new'
    end
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      @record.update_column(:timeend, Time.now.next_day)
      RecordsCloseJob.set(wait: 0.seconds).perform_later(@record) if record_params[:status] == 'Аукцион закрыт'
      redirect_to @record
    else
      render 'edit'
    end
  end

  def destroy
    @record = Record.find(params[:id])
    unless @record.status == 'Аукцион закрыт'
      @record.comments.each do |item|
        usr = User.find_by(email: item.username)
        usr.balance += item.cost
        usr.save
      end
    end
    @record.destroy
    redirect_to records_path
  end

  private

  def record_params
    params.require(:record).permit(:title, :photo, :description, :status)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# class SessionsController
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: (t '.log_suc')
    else
      flash.now[:alert] = t '.log_err'
      render 'new'
    end
  end

  def destroy
    # deletes user session
    session[:user_id] = nil
    redirect_to root_path, notice: (t '.log_out')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# class UsersController
class UsersController < ApplicationController
  before_action :require_user_logged_in!, only: %i[edit update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      WelcomeMailer.with(user: @user).welcome_email.deliver_now
      session[:user_id] = @user.id
      redirect_to root_path, notice: (t '.cr_acc')
    else
      render 'new'
    end
  end

  def edit; end

  def update
    return unless balance_params[:balance].to_i.positive?

    Current.user.balance += balance_params[:balance].to_i
    if Current.user.save
      redirect_to edit_balance_path, notice: (t '.bal_upd')
    else
      render 'edit'
    end
  end

  private

  def balance_params
    params.require(:user).permit(:balance)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# module ApplicationHelper
module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# module CommentsHelper
module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# module PagesHelper
module PagesHelper
end

app/helpers/password_resets_helper.rb
# frozen_string_literal: true

# module PasswordResetsHelper
module PasswordResetsHelper
end

app/helpers/records_helper.rb
# frozen_string_literal: true

# module RecordsHelper
module RecordsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# module SessionsHelper
module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# module UsersHelper
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <script src="https://bot.jaicp.com/chatwidget/zWQxjokj:15fd0b451adb699402a66f07d4b7a86af7ca4ccc/justwidget.js?force=true" async></script>
  <div>

  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="<%= root_path %>" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <image src="https://i.pinimg.com/originals/a6/25/cc/a625cc89bdcf3cbb0c7940e604db01b9.png" src="yourfallback.png" width="70" height="40"/>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="<%= home_path %>" class="nav-link px-2 text-secondary"><%= t 'global.main' %></a></li>
          <li><a href="<%= about_path %>" class="nav-link px-2 text-white"><%= t 'global.about' %></a></li>
          <li>
            <% flash.each do |type, msg| %>
            <div class="hidethis"><p class="<%= 'my'+type.to_s %>"><%=msg %></p></div>
            <% end %>
          </li>
        </ul>
        <div class="text-end">
          <table style="border-collapse: separate;border-spacing: 10px 0px;">
            <tr>
              <% if Current.user %>
                    <td style="text-align: center; vertical-align: middle;"><%= t 'global.log_as'%><%=Current.user.email %></td>
                    <td style="text-align: center; vertical-align: middle;"><%= t 'global.balance'%><%= Current.user.balance %></td>
                    <td style="text-align: center; vertical-align: middle;"><%= button_to (t 'global.account'), edit_balance_path, method: :get, class: "btn btn-outline-light me-2" %></td>
                    <td style="text-align: center; vertical-align: middle;"><%= button_to (t 'global.logout'), logout_path, method: :delete, class: "btn btn-outline-light me-2" %></td>
              <% else %>
                    <td style="text-align: center; vertical-align: middle;"><%= button_to (t 'global.sign_up'), sign_up_path, method: :get, class: "btn btn-warning" %></td>
                    <td style="text-align: center; vertical-align: middle;"><%= button_to (t 'global.login'), sign_in_path, method: :get,  class: "btn btn-outline-light me-2" %></td>
              <% end %>
              <% I18n.available_locales.each do |locale| %>
                <% if locale != I18n.locale %>
                  <td><%= link_to t(locale), "/#{locale}/#{request.env['PATH_INFO'][4..-1]}", class: "nav-link" %></td>
                <% end %>
              <% end %>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1><%= t '.about' %></h1>
  <p><%= t '.lang' %></p>
</div>

app/views/pages/mainpage.html.erb
<main class="qqqqq px-3 justify-content-center align-items-center" style="width: 100%; height: 100vh">
  <h1><%= t '.auction' %></h1>
  <p class="lead" style="text-align:justify"><%= t '.auto_text' %></p>
  <p class="lead" style="text-align:justify"><%= t '.auto_text2' %></p>
  <p class="lead"><%= t '.valt_text' %></p>
  <p class="lead">
    <a href="<%= home_path %>" class="btn btn-lg btn-secondary fw-bold border-black bg-black"><%= t '.find' %></a>
  </p>
</main>

app/views/password_resets/edit.html.erb
<div class="container">
  <h1><%= t '.reset_p' %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), data: { turbo: false }  do |f| %>
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
        <% end %>
        <p>
          <%= f.label :password %><br />
          <%= f.password_field :password, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </p>
        <p>
          <%= f.submit (t '.reset'), class: "btn btn-primary" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="container">
  <h1><%= t 'sessions.new.fp' %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with url: password_reset_path do |f| %>
        <p>
          <%= f.label t 'sessions.new.email' %><br />
          <%= f.text_field :email, class: 'form-control' %>
        </p>
        <p>
          <%= f.submit (t '.to_null'), class: "btn btn-primary" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/records/edit.html.erb
<div class="container">
<h2><%= t '.edit_rec' %></h2>
<%= form_for @record, data: { turbo: false }  do |f| %>
  <% if @record.errors.any? %>
    <% @record.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, class:'form-control' %>
  </p>
  <p>
    <%= f.label :status %>
    <%=f.select :status, ['Аукцион объявлен','Аукцион закрыт']%></p>
  <p>
  <p>
    <%= f.submit (t '.edit'), class: 'btn btn-success' %>
  </p>
<% end %>
</div>

app/views/records/index.html.erb
<div class="container">
  <% if @is_admin %>
    <%= button_to (t '.new'), new_record_path,method: :get, :class => 'btn btn-success', :style => 'margin-top: 5px' %>
  <%end %>
<h1><%= t '.cnt' %><span  id="cntrec"><%=Record.count %></span></h1>
<% @record.each do |record| %>
  <%=content_tag(:div, '', :class => (record.status == 'Аукцион объявлен' ? 'card mb-3 border-success' : 'card mb-3 border-danger'), :style => "max-width: 1500px" )do %>
    <div class="row g-0">
      <div class="col-md-3" style="display:inline-block; position:relative;">
        <% if record.status == 'Аукцион объявлен'%>
          <%= image_tag record.photo, size: "310x200", crop: :fill, style: "border-radius: 5px" %>
          <h5 class="card-text" style="text-align: center; letter-spacing: 5px;"><%= t '.max_cost' %><%= record.comments.maximum("cost") %>$</h5>
          <% else %>
        <%= image_tag record.photo, size: "310x200", crop: :fill, style: 'filter: blur(3px);' %>
        <p style="display: inline-block; position: absolute; bottom: 85px; left: 0px;  padding: -5px -5px -5px -10px;
          color:red; letter-spacing: 5px; font-weight: bold; font-size: 26px; transform: rotate(-30deg); border: 3px solid red;"><%= record.status %></p>
        <h5 class="card-text" style="text-align: center; letter-spacing: 5px;"><%= t '.car_sell' %><%= record.comments.maximum("cost") %>$</h5>
      <% end %>
      </div>
      <div class="col-md-9">
        <div class="card-body">
          <h3 class="card-title"><%= record.title %></h3>
          <p class="card-text"><%= record.description[0..200] %>...<p>
          <% if record.status == 'Аукцион объявлен'%>
            <p class="card-text"><small class="text-muted"><%= t '.to_end' %><span class="time" id=<%= record.id %> time="<%= record.timeend-Time.now %>">0</span></small></p>
        <% else %>
            <p class="card-text"><small class="text-muted"><%= t '.to_end' %>00 : 00 : 00</small></p>
          <% end %>
            </div>
        <div class="card-footer"><%= link_to (t '.more'), record_path(record), :class => 'btn btn-outline-primary', style: 'text-align:center;display:block;'%></div>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/records/new.html.erb
<div class="container">
<h2><%= t '.add_rec' %></h2>
<%= form_for :record, url: records_path, data: { turbo: false }  do |f| %>
  <% if @record.errors.any? %>
    <% @record.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :photo %>
    <%= f.file_field :photo, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :status %>
    <%=f.select :status, ['Аукцион объявлен','Аукцион закрыт']%></p>
  <p>
    <%= f.submit (t '.create'), class: 'btn btn-success' %>
  </p>
<% end %>
</div>

app/views/records/show.html.erb
<div class="container">
  <div class="card mb-3 border-dark" style="max-width: 1500px; top: 5px">
    <div class="row g-0">
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title"><%= @record.title %></h3>
          <p class="card-text"><%= @record.description %></p>
          <h5 class="card-text" style="bottom: 1px"><%= @record.status %></h5>
        </div>
        <% if @is_admin %>
          <table style="position: absolute; bottom: 5px; left: 10px">
            <tr>
              <td><%= button_to (t '.edit'), edit_record_path(@record),method: :get, :class => 'btn btn-warning' %></td>
              <td><%= button_to (t '.delete'), record_path(@record), method: :delete, data: {turbo_confirm: (t 'global.del_sure')}, :class => 'btn btn-danger' %></td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="col-md-4">
          <%= image_tag @record.photo, size: "430x270", crop: :fill %>
      </div>
    </div>
  </div>
  <h2><%= t '.all_bet' %></h2>
  <% @record.comments.each do |comment| %>
    <div class="alert alert-light">
      <p><strong><%= comment.username %></strong>: <%=comment.cost %></p>
    </div>
  <% end %>
  <% unless @is_admin %>
    <% if @record.comments.where(username: Current.user.email).count < 1 && @record.status == 'Аукцион объявлен'%>
      <hr>
      <h2><%= t '.add_bet' %></h2>
      <%= form_for ([@record, @record.comments.build]) do |f| %>
        <p>
          <%= f.label :cost %>
          <%= f.number_field :cost, class: 'form-control', min: 0 %>
        </p>
        <p>
          <%= f.submit (t '.add'), class: 'btn btn-success' %>
        </p>
      <% end %>
    <% else if @record.comments.where(username: Current.user.email).count == 1 && @record.status == 'Аукцион объявлен'%>
      <hr>
      <h2><%= t '.bet_com' %></h2>
      <% else %>
        <hr>
        <h2><%= t '.pay_car' %><%= @record.comments.maximum("cost") %>$</h2>
      <% end %>
    <%end %>
  <%end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1><%= t '.add_money' %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: Current.user, url: edit_balance_path, data: { turbo: false } do |f| %>
        <% if Current.user.errors.any? %>
          <% Current.user.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
        <% end %>
        <p>
          <%= f.label :balance%><br>
          <%= f.number_field :balance, value:0, class: 'form-control', min: 0, max: 100000 %>
        </p>
        <p>
          <%= f.submit (t '.update'), class: "btn btn-primary" %>
        </p>
      <% end %>
    </div>
  </div>
  <% Record.all.each do |record| %>
    <% unless record.comments.find_by(username: Current.user.email).nil?%>
      <%=content_tag(:div, '', :class => (record.status == 'Аукцион объявлен' ? 'card mb-3 border-success' : 'card mb-3 border-danger'), :style => "max-width: 1500px" )do %>
        <div class="row g-0">
          <div class="col-md-3" style="display:inline-block; position:relative;">
            <% if record.status == 'Аукцион объявлен'%>
              <%= image_tag record.photo, size: "310x200", crop: :fill, style: "border-radius: 5px" %>
              <h5 class="card-text" style="text-align: center; letter-spacing: 5px;"><%= t 'records.index.max_cost' %><%= record.comments.maximum("cost") %>$</h5>
            <% else %>
              <%= image_tag record.photo, size: "310x200", crop: :fill, style: 'filter: blur(3px);' %>
              <p style="display: inline-block; position: absolute; bottom: 85px; left: 0px;  padding: -5px -5px -5px -10px;
                color:red; letter-spacing: 5px; font-weight: bold; font-size: 26px; transform: rotate(-30deg); border: 3px solid red;"><%= record.status %></p>
              <h5 class="card-text" style="text-align: center; letter-spacing: 5px;"><%= t 'records.index.car_sell' %><%= record.comments.maximum("cost") %>$</h5>
            <% end %>
          </div>
          <div class="col-md-9">
            <div class="card-body">
              <h3 class="card-title"><%= record.title %></h3>
              <p class="card-text"><%= record.description[0..200] %>...<p>
              <% if record.status == 'Аукцион объявлен'%>
                <p class="card-text"><small class="text-muted"><%= t 'records.index.to_end' %><span class="time" id=<%= record.id %> time="<%= record.timeend-Time.now %>">0</span></small></p>
              <% else %>
                <p class="card-text"><small class="text-muted"><%= t 'records.index.to_end' %>00:00:00</small></p>
              <% end %>
            </div>
            <div class="card-footer"><%= link_to (t 'records.index.more'), record_path(record), :class => 'btn btn-outline-primary', style: 'text-align:center;display:block;'%></div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
<h1><%= t '.sign_up' %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, url: sign_up_path, data: { turbo: false } do |f| %>
      <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
      <% end %>
      <p>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </p>
      <p>
      <%= f.submit (t '.create_acc'), class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>
</div>